PREFIX pl: <https://peculiarlibrarian.org/ontology/>

SELECT ?competency
       (COUNT(?evidence) AS ?evidenceCount)
WHERE {

    ?competency a pl:Competency .

    OPTIONAL {
        ?evidence
            pl:supportsCompetency ?competency .
    }

}
GROUP BY ?competency
ORDER BY DESC(?evidenceCount)

