PREFIX pl: <https://peculiarlibrarian.org/ontology/>

SELECT ?person ?opportunity
WHERE {
    ?person a pl:Person ;
            pl:hasCompetency ?competency .

    ?opportunity a pl:Opportunity ;
                 pl:requiresCompetency ?competency .
}
