PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX pl: <https://peculiarlibrarian.org/ontology/>

SELECT
    ?pipeline

WHERE {

    ?pipeline
        rdf:type
        pl:Pipeline .

}
ORDER BY ?pipeline
