PREFIX fin: <https://peculiarlibrarian.org/finance/>

SELECT ?year ?revenue ?net_profit ?eps ?fcf ?net_margin ?fcf_conversion
WHERE {
    ?obs a fin:Observation ;
         fin:hasReportingPeriod ?year ;
         fin:hasMetric ?metric .

    OPTIONAL { ?obs fin:revenue ?revenue }
    OPTIONAL { ?obs fin:net_profit ?net_profit }
    OPTIONAL { ?obs fin:eps ?eps }
    OPTIONAL { ?obs fin:fcf ?fcf }
    OPTIONAL { ?obs fin:net_margin ?net_margin }
    OPTIONAL { ?obs fin:fcf_conversion ?fcf_conversion }
}
